{
  "openapi": "3.0.1",
  "info": {
    "version": "1.0.0",
    "title": "Petlove",
    "description": "Petlove backend"
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [{ "url": "http://localhost:6004/api" }],
  "tags": [
    {
      "name": "Users",
      "description": "Users endpoints"
    },
    {
      "name": "Notices",
      "description": "Notices endpoints"
    },
    {
      "name": "Cities",
      "description": "Cities endpoints"
    },
    {
      "name": "Friends",
      "description": "Friends endpoints"
    },
    {
      "name": "News",
      "description": "News endpoints"
    }
  ],
  "paths": {
    "/users/signup": {
      "post": {
        "tags": ["Users"],
        "summary": "User sign up",
        "requestBody": {
          "description": "Sign up object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SignUpRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SignUpResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Service not found",
            "content": {}
          },
          "409": {
            "description": "Such email already exists",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/users/signin": {
      "post": {
        "tags": ["Users"],
        "summary": "User sign in",
        "requestBody": {
          "description": "Sign in object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SignInRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SignInResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": "Email or password invalid",
            "content": {}
          },
          "404": {
            "description": "Service not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/users/current": {
      "get": {
        "tags": ["Users"],
        "summary": "Get current user info",
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetCurrentResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          },
          "404": {
            "description": "Service not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/users/signout": {
      "post": {
        "tags": ["Users"],
        "summary": "User sign out",
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SignOutResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          },
          "404": {
            "description": "Service not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/notices": {
      "get": {
        "tags": ["Notices"],
        "summary": "Get notices",
        "security": [],
        "parameters": [
          {
            "in": "query",
            "name": "keyword",
            "description": "The keyword for searching",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "category",
            "description": "The category for searching",
            "schema": {
              "type": "string",
              "enum": ["sell", "free", "lost", "found"]
            }
          },
          {
            "in": "query",
            "name": "species",
            "description": "The species for searching",
            "schema": {
              "type": "string",
              "enum": ["dog", "cat", "monkey", "bird", "snake", "turtle", "lizard", "frog", "fish", "ants", "bees", "butterfly", "spider", "scorpion"]
            }
          },
          {
            "in": "query",
            "name": "locationId",
            "description": "The location id for searching",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "byDate",
            "description": "Sort notices by date",
            "schema": {
              "type": "boolean",
              "default": true
            }
          },
          {
            "in": "query",
            "name": "byPrice",
            "description": "Sort notices by price",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "in": "query",
            "name": "byPopularity",
            "description": "Sort notices by popularity",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "in": "query",
            "name": "page",
            "description": "The number page of the notices",
            "schema": {
              "type": "number",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "limit",
            "description": "The limit for the notices",
            "schema": {
              "type": "number",
              "default": 6
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetNoticesResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/notices/categories": {
      "get": {
        "tags": ["Notices"],
        "summary": "Get notice categories",
        "security": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetNoticeCategoriesResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/notices/sex": {
      "get": {
        "tags": ["Notices"],
        "summary": "Get notice sex",
        "security": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetNoticeSexResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/notices/species": {
      "get": {
        "tags": ["Notices"],
        "summary": "Get notice species",
        "security": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetNoticeSpeciesResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/notices/favorites/add/{id}": {
      "post": {
        "tags": ["Notices"],
        "summary": "Add a notice to user favorites",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "query",
            "name": "id",
            "description": "The notice id",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddNoticeToUserFavoritesResponse"
                }
              }
            }
          },
          "400": {
            "description": "This id is not valid",
            "content": {}
          },
          "404": {
            "description": "This notice is not found in notices",
            "content": {}
          },
          "409": {
            "description": "This notice has already added to user's favorite notices",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/notices/favorites/remove/{id}": {
      "delete": {
        "tags": ["Notices"],
        "summary": "Remove a notice from user favorites",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "query",
            "name": "id",
            "description": "The notice id",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RemoveNoticeToUserFavoritesResponse"
                }
              }
            }
          },
          "400": {
            "description": "This id is not valid",
            "content": {}
          },
          "404": {
            "description": "This notice is not found in notices",
            "content": {}
          },
          "409": {
            "description": "This notice is not found in user's favorite notices",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/notices/{id}": {
      "get": {
        "tags": ["Notices"],
        "summary": "Get a notice by id",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "Notice id",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetNoticeByIdResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "This notice is not found in notices",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/cities/": {
      "get": {
        "tags": ["Cities"],
        "summary": "Get Ukrainian cities",
        "security": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetCitiesResponse"
                }
              }
            }
          },
          "404": {
            "description": "Service not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/friends/": {
      "get": {
        "tags": ["Friends"],
        "summary": "Get Petlove friends",
        "security": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetFriendsResponse"
                }
              }
            }
          },
          "404": {
            "description": "Service not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/news": {
      "get": {
        "tags": ["News"],
        "summary": "Get news",
        "security": [],
        "parameters": [
          {
            "in": "query",
            "name": "keyword",
            "description": "The keyword for searching",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "page",
            "description": "The number page of the news",
            "schema": {
              "type": "number",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "limit",
            "description": "The limit for the news",
            "schema": {
              "type": "number",
              "default": 6
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetNewsResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "SignUpRequest": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "name": {
            "type": "string",
            "description": "User name as string",
            "example": "TestName"
          },
          "email": {
            "type": "string",
            "description": "User email as a string with a valid email address format",
            "example": "test@gmail.com"
          },
          "password": {
            "type": "string",
            "description": "User password as a string which consists of 7 symbols",
            "example": "1234567"
          }
        }
      },
      "SignUpResponse": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User name",
            "example": "TestName"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "example": "test@gmail.com"
          },
          "token": {
            "type": "string",
            "description": "User token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjA3MDAzOTJhMjMxNWFiODk2MGMxYiIsImlhdCI6MTY4OTI4NDYxMiwiZXhwIjoxNjg5MzY3NDEyfQ.a8GLmpGRC0BWzhLyd2UVTpH0Cp6j-m9hrxu4MCnaQPM"
          }
        },
        "example": {
          "email": "test@gmail.com",
          "name": "TestName",
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjA3MDAzOTJhMjMxNWFiODk2MGMxYiIsImlhdCI6MTY4OTI4NDYxMiwiZXhwIjoxNjg5MzY3NDEyfQ.a8GLmpGRC0BWzhLyd2UVTpH0Cp6j-m9hrxu4MCnaQPM"
        }
      },
      "SignInRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User email as a string with a valid email address format",
            "example": "test@gmail.com"
          },
          "password": {
            "type": "string",
            "description": "User password as a string which consists of 7 symbols",
            "example": "1234567"
          }
        }
      },
      "SignInResponse": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "User email",
            "example": "test@gmail.com"
          },
          "name": {
            "type": "string",
            "description": "User name",
            "example": "TestName"
          },
          "token": {
            "type": "string",
            "description": "User token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjA3MDAzOTJhMjMxNWFiODk2MGMxYiIsImlhdCI6MTY4OTI4NDYxMiwiZXhwIjoxNjg5MzY3NDEyfQ.a8GLmpGRC0BWzhLyd2UVTpH0Cp6j-m9hrxu4MCnaQPM"
          }
        },
        "example": {
          "email": "test@gmail.com",
          "name": "TestName",
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjA3MDAzOTJhMjMxNWFiODk2MGMxYiIsImlhdCI6MTY4OTI4Nzg0OCwiZXhwIjoxNjg5MzcwNjQ4fQ.LoDGkboiEfTDoAvt6edVXGdKErdcaby5RJ6n5HS5VHg"
        }
      },
      "GetCurrentResponse": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "description": "User id",
            "example": "64b1e25f6b0a2ccb95591ec7"
          },
          "name": {
            "type": "string",
            "description": "User name",
            "example": "TestName"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "example": "test@gmail.com"
          },
          "token": {
            "type": "string",
            "description": "User token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjFlMjVmNmIwYTJjY2I5NTU5MWVjNyIsImlhdCI6MTY4OTM3OTQyMywiZXhwIjoxNjg5NDYyMjIzfQ.hT2Ta6pBhDR1vOF7LjcKxofyASDPjcTZtFi9CESKIuA"
          },
          "noticesFavorites": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string",
                  "description": "Notice id",
                  "example": "64b3258eec20387954fa7093"
                },
                "species": {
                  "type": "string",
                  "description": "Pet species",
                  "example": "dog"
                },
                "category": {
                  "type": "string",
                  "description": "Notice category",
                  "example": "sell"
                },
                "price": {
                  "type": "number",
                  "description": "Pet price",
                  "example": 100
                },
                "title": {
                  "type": "string",
                  "description": "Notice title",
                  "example": "Sell a cute husky"
                },
                "name": {
                  "type": "string",
                  "description": "Pet name",
                  "example": "Rex"
                },
                "birthday": {
                  "type": "string",
                  "description": "Pet birthday",
                  "example": "2021-01-01"
                },
                "comment": {
                  "type": "string",
                  "description": "Notice comment",
                  "example": "Sell a cute husky"
                },
                "sex": {
                  "type": "string",
                  "description": "Pet sex",
                  "example": "male"
                },
                "location": {
                  "type": "string",
                  "description": "Pet location id",
                  "example": "641ffcc1ae4e889a02d25ca5"
                },
                "imgURL": {
                  "type": "string",
                  "description": "Pet image url",
                  "example": "https://ftp.goit.study/img/pets/1.webp"
                },
                "user": {
                  "type": "string",
                  "description": "Notice author",
                  "example": "641ffcc1ae4e889a02d25ca5"
                },
                "popularity": {
                  "type": "number",
                  "description": "Notice popularity",
                  "example": 100
                }
              }
            }
          }
        },
        "example": {
          "_id": "658e94c4ef5b4b3b6f1cdc94",
          "name": "testname",
          "email": "testdw@gmail.com",
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OGU5NGM0ZWY1YjRiM2I2ZjFjZGM5NCIsImlhdCI6MTcwMzg0MzAxMywiZXhwIjoxNzAzOTI1ODEzfQ.y7ZymOcmw0iCmujzU1yIS6gaf4hyYKh919xg3QoTGl4",
          "noticesFavorites": [
            {
              "_id": "6589436d05a6bcd9b9379423",
              "species": "turtle",
              "category": "found",
              "title": "Found Red-Eared Slider",
              "name": "Shelly",
              "birthday": "2019-12-08",
              "comment": "Found this turtle near the pond. Contact if yours.",
              "sex": "unknown",
              "location": "641ffcd3ae4e889a02d29c75",
              "imgURL": "https://ftp.goit.study/img/pets/5.webp",
              "createdAt": "2023-12-11T10:43:28.477Z",
              "user": "6576e7d0c4cc99fc5ef94221",
              "popularity": 3,
              "updatedAt": "2023-12-25T11:30:37.762Z"
            }
          ]
        }
      },
      "SignOutResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "Sign out success",
            "example": "Sign out success"
          }
        },
        "example": {
          "message": "Sign out success"
        }
      },
      "GetNoticesResponse": {
        "type": "object",
        "properties": {
          "results": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string",
                  "description": "Notice id",
                  "example": "654fc4d00a563c69b09895ef"
                },
                "species": {
                  "type": "string",
                  "description": "Pet species",
                  "example": "dog"
                },
                "category": {
                  "type": "string",
                  "description": "Notice category",
                  "example": "sell"
                },
                "price": {
                  "type": "number",
                  "description": "Pet price",
                  "example": 150
                },
                "title": {
                  "type": "string",
                  "description": "Notice title",
                  "example": "Golden Retriever Puppies"
                },
                "name": {
                  "type": "string",
                  "description": "Pet name",
                  "example": "Max"
                },
                "birthday": {
                  "type": "string",
                  "description": "Pet birthday",
                  "example": "2022-01-10"
                },
                "comment": {
                  "type": "string",
                  "description": "Notice comment",
                  "example": "Adorable puppy looking for a loving home."
                },
                "sex": {
                  "type": "string",
                  "description": "Pet sex",
                  "example": "male"
                },
                "location": {
                  "type": "string",
                  "description": "Pet location id",
                  "example": "641ffcc1ae4e889a02d25ca5"
                },
                "imageUrl": {
                  "type": "string",
                  "description": "Pet image url",
                  "example": "https://ftp.goit.study/img/pets/1.webp"
                },
                "popularity": {
                  "type": "number",
                  "description": "Notice popularity",
                  "example": 2
                },
                "user": {
                  "type": "string",
                  "description": "Notice author id",
                  "example": "6576e7d0c4cc99fc5ef94221"
                },
                "createdAt": {
                  "type": "string",
                  "description": "Notice date of the creating",
                  "example": "2023-12-11T10:43:28.477Z"
                },
                "updatedAt": {
                  "type": "string",
                  "description": "Notice date of the updating",
                  "example": "2023-12-25T11:41:12.493Z"
                }
              }
            }
          },
          "totalPages": {
            "type": "number"
          },
          "page": {
            "type": "number"
          },
          "perPage": {
            "type": "number"
          }
        },
        "example": {
          "page": 1,
          "perPage": 2,
          "totalPages": 26,
          "results": [
            {
              "_id": "6589436d05a6bcd9b9379420",
              "species": "dog",
              "category": "sell",
              "price": 150,
              "title": "Golden Retriever Puppies",
              "name": "Max",
              "birthday": "2022-01-10",
              "comment": "Adorable puppy looking for a loving home.",
              "sex": "male",
              "location": "641ffcc1ae4e889a02d25ca5",
              "imgURL": "https://ftp.goit.study/img/pets/1.webp",
              "createdAt": "2023-12-11T10:43:28.477Z",
              "user": "6576e7d0c4cc99fc5ef94221",
              "popularity": 2,
              "updatedAt": "2023-12-25T11:41:12.493Z"
            },
            {
              "_id": "6589436d05a6bcd9b9379421",
              "species": "fish",
              "category": "free",
              "title": "Colorful Betta Fish",
              "name": "Splash",
              "birthday": "2021-04-05",
              "comment": "Free to a good home. Beautiful betta fish.",
              "sex": "unknown",
              "location": "641ffcd2ae4e889a02d28d11",
              "imgURL": "https://ftp.goit.study/img/pets/3.webp",
              "createdAt": "2023-12-11T10:43:28.477Z",
              "user": "6576e7d0c4cc99fc5ef94221",
              "popularity": 1
            }
          ]
        }
      },
      "GetNoticeCategoriesResponse": {
        "type": "array",
        "items": {
          "type": "string",
          "description": "Notice category",
          "example": "found"
        },
        "example": ["found", "free", "lost", "sell"]
      },
      "GetNoticeSexResponse": {
        "type": "array",
        "items": {
          "type": "string",
          "description": "Pet sex",
          "example": "male"
        },
        "example": ["female", "male", "multiple", "unknown"]
      },
      "GetNoticeSpeciesResponse": {
        "type": "array",
        "items": {
          "type": "string",
          "description": "Pet species",
          "example": "dog"
        },
        "example": ["dog", "cat", "monkey", "bird", "snake", "turtle", "lizard", "frog", "fish", "ants", "bees", "butterfly", "spider", "scorpion"]
      },
      "AddNoticeToUserFavoritesResponse": {
        "type": "array",
        "items": {
          "type": "string",
          "description": "Notice id",
          "example": "6589436d05a6bcd9b9379425"
        },
        "example": ["6589436d05a6bcd9b9379425", "6589436d05a6bcd9b9379423"]
      },
      "RemoveNoticeToUserFavoritesResponse": {
        "type": "array",
        "items": {
          "type": "string",
          "description": "Notice id",
          "example": "6589436d05a6bcd9b9379425"
        },
        "example": ["6589436d05a6bcd9b9379425", "6589436d05a6bcd9b9379423"]
      },
      "GetNoticeByIdResponse": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "description": "Notice id",
            "example": "6589436d05a6bcd9b9379425"
          },
          "species": {
            "type": "string",
            "description": "Pet species",
            "example": "bird"
          },
          "category": {
            "type": "string",
            "description": "Notice category",
            "example": "free"
          },
          "title": {
            "type": "string",
            "description": "Notice title",
            "example": "Canary Looking for a Home"
          },
          "name": {
            "type": "string",
            "description": "Pet name",
            "example": "Sunny"
          },
          "birthday": {
            "type": "string",
            "description": "Pet birthday",
            "example": "2020-03-12"
          },
          "comment": {
            "type": "string",
            "description": "Notice comment",
            "example": "Free to a caring owner. Beautiful canary."
          },
          "sex": {
            "type": "string",
            "description": "Pet sex",
            "example": "male"
          },
          "location": {
            "type": "object",
            "properties": {
              "_id": {
                "type": "string",
                "description": "Pet location id",
                "example": "641ffcc3ae4e889a02d26d45"
              },
              "stateEn": {
                "type": "string",
                "description": "Pet location state",
                "example": "Dnipropetrovska"
              },
              "cityEn": {
                "type": "string",
                "description": "Pet location city",
                "example": "Dnipro"
              }
            }
          },
          "imgUrl": {
            "type": "string",
            "description": "Pet image url",
            "example": "https://ftp.goit.study/img/pets/7.webp"
          },
          "popularity": {
            "type": "number",
            "description": "Notice popularity",
            "example": 2
          },
          "user": {
            "type": "object",
            "properties": {
              "_id": {
                "type": "string",
                "description": "Notice author id",
                "example": "6576e7d0c4cc99fc5ef94221"
              },
              "email": {
                "type": "string",
                "description": "Notice author email",
                "example": "test@gmail.com"
              },
              "phone": {
                "type": "string",
                "description": "Notice author phone",
                "example": "+380730000000"
              }
            }
          },
          "createdAt": {
            "type": "string",
            "description": "Notice date of the creating",
            "example": "2023-12-11T10:43:28.477Z"
          },
          "updatedAt": {
            "type": "string",
            "description": "Notice date of the updating",
            "example": "2023-12-25T11:41:12.493Z"
          }
        },
        "example": {
          "_id": "6589436d05a6bcd9b9379425",
          "species": "bird",
          "category": "free",
          "title": "Canary Looking for a Home",
          "name": "Sunny",
          "birthday": "2020-03-12",
          "comment": "Free to a caring owner. Beautiful canary.",
          "sex": "male",
          "location": {
            "_id": "641ffcc3ae4e889a02d26d45",
            "stateEn": "Dnipropetrovska",
            "cityEn": "Dnipro"
          },
          "imgURL": "https://ftp.goit.study/img/pets/7.webp",
          "createdAt": "2023-12-11T10:43:28.477Z",
          "user": {
            "_id": "6576e7d0c4cc99fc5ef94221",
            "email": "test@gmail.com",
            "phone": "+380730000000"
          },
          "popularity": 2,
          "updatedAt": "2023-12-29T20:50:09.235Z"
        }
      },
      "GetCitiesResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "City id",
              "example": "641ffcd4ae4e889a02d2a3d4"
            },
            "stateEn": {
              "type": "string",
              "description": "State name",
              "example": "Poltavska"
            },
            "cityEn": {
              "type": "string",
              "description": "City name",
              "example": "Poltava"
            },
            "countyEn": {
              "type": "string",
              "description": "County name",
              "example": "Poltavska"
            }
          }
        },
        "example": [
          {
            "_id": "641ffcd5ae4e889a02d2b2f5",
            "useCounty": "0",
            "stateEn": "Lvivska",
            "cityEn": "Reklynets",
            "countyEn": "Sokalskyy"
          },
          {
            "_id": "641ffcd5ae4e889a02d2b31c",
            "useCounty": "0",
            "stateEn": "Lvivska",
            "cityEn": "Kulychkiv",
            "countyEn": "Sokalskyy"
          },
          {
            "_id": "641ffcd5ae4e889a02d2b32a",
            "useCounty": "0",
            "stateEn": "Lvivska",
            "cityEn": "Zarika",
            "countyEn": "Sokalskyy"
          }
        ]
      },
      "GetFriendsResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "Friend id",
              "example": "658b664c05a6bcd9b937945c"
            },
            "title": {
              "type": "string",
              "description": "Company name",
              "example": "Sirius"
            },
            "url": {
              "type": "string",
              "description": "Company url",
              "example": "https://dogcat.com.ua"
            },
            "addressUrl": {
              "type": "string",
              "description": "Company address url",
              "example": "https://goo.gl/maps/iq8NXEUf31EAQCzc6"
            },
            "address": {
              "type": "string",
              "description": "Company address",
              "example": "Fedorivka, Kyiv Oblast, Ukraine, 07372"
            },
            "imageUrl": {
              "type": "string",
              "description": "Company image url",
              "example": "https://ftp.goit.study/img/petsfriends/1.webp"
            },
            "workDays": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string",
                    "description": "Day id",
                    "example": "658f39fccc54e981e2d98778"
                  },
                  "isOpen": {
                    "type": "boolean",
                    "description": "Company is open or not",
                    "example": false
                  }
                }
              }
            },
            "phone": {
              "type": "string",
              "description": "Company phone",
              "example": "+380931934069"
            },
            "email": {
              "type": "string",
              "description": "Company email",
              "example": "dogcat.sirius@gmail.com"
            }
          }
        },
        "example": [
          {
            "_id": "658b664c05a6bcd9b937945c",
            "title": "Sirius",
            "url": "https://dogcat.com.ua",
            "addressUrl": "https://goo.gl/maps/iq8NXEUf31EAQCzc6",
            "imageUrl": "https://ftp.goit.study/img/petsfriends/1.webp",
            "address": "Fedorivka, Kyiv Oblast, Ukraine, 07372",
            "workDays": [
              {
                "_id": "658f39fccc54e981e2d98778",
                "isOpen": false
              },
              {
                "_id": "658f39fccc54e981e2d98779",
                "isOpen": false
              },
              {
                "_id": "658f39fccc54e981e2d9877a",
                "isOpen": false
              },
              {
                "_id": "658f39fccc54e981e2d9877b",
                "isOpen": false
              },
              {
                "_id": "658f39fccc54e981e2d9877c",
                "isOpen": false
              },
              {
                "_id": "658f39fccc54e981e2d9877d",
                "isOpen": true,
                "from": "11:00",
                "to": "16:00"
              },
              {
                "_id": "658f39fccc54e981e2d9877e",
                "isOpen": true,
                "from": "11:00",
                "to": "16:00"
              }
            ],
            "phone": "+380931934069",
            "email": "dogcat.sirius@gmail.com"
          },
          {
            "_id": "658b664c05a6bcd9b937945d",
            "title": "Happy Paw",
            "url": "https://happypaw.ua/ua",
            "addressUrl": "https://goo.gl/maps/3RyzTYBvMr9WQWCC6",
            "imageUrl": "https://ftp.goit.study/img/petsfriends/2.webp",
            "address": "44 Shota Rustaveli Street, Kyiv (3rd floor, office 7)",
            "workDays": [
              {
                "_id": "658f39fccc54e981e2d9877f",
                "isOpen": true,
                "from": "09:00",
                "to": "17:00"
              },
              {
                "_id": "658f39fccc54e981e2d98780",
                "isOpen": true,
                "from": "09:00",
                "to": "17:00"
              },
              {
                "_id": "658f39fccc54e981e2d98781",
                "isOpen": true,
                "from": "09:00",
                "to": "17:00"
              },
              {
                "_id": "658f39fccc54e981e2d98782",
                "isOpen": true,
                "from": "09:00",
                "to": "17:00"
              },
              {
                "_id": "658f39fccc54e981e2d98783",
                "isOpen": true,
                "from": "09:00",
                "to": "17:00"
              },
              {
                "_id": "658f39fccc54e981e2d98784",
                "isOpen": true,
                "from": "09:00",
                "to": "17:00"
              },
              {
                "_id": "658f39fccc54e981e2d98785",
                "isOpen": true,
                "from": "09:00",
                "to": "17:00"
              }
            ],
            "phone": "+380442900329",
            "email": "hello@happypaw.ua"
          }
        ]
      },
      "GetNewsResponse": {
        "type": "object",
        "properties": {
          "results": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string",
                  "description": "News id",
                  "example": "658b694505a6bcd9b9379466"
                },
                "imgUrl": {
                  "type": "string",
                  "description": "News image url",
                  "example": "https://www.nytimes.com/images/2023/04/16/magazine/16mag-LOR/16mag-LOR-blog480.jpg"
                },
                "title": {
                  "type": "string",
                  "description": "News title",
                  "example": "What I Learned Dogsitting for New York City's Opulent Elite"
                },
                "text": {
                  "type": "string",
                  "description": "News text",
                  "example": "In a city of yawning class inequality, some side hustles let you glimpse how the other half lives."
                },

                "date": {
                  "type": "string",
                  "description": "News date",
                  "example": "2023-04-11T09:00:18+0000"
                },
                "url": {
                  "type": "string",
                  "description": "News url",
                  "example": "https://www.nytimes.com/2023/04/11/magazine/dogsitting-rich-new-york.html"
                }
              }
            }
          },
          "totalPages": {
            "type": "number"
          },
          "page": {
            "type": "number"
          },
          "perPage": {
            "type": "number"
          }
        },
        "example": {
          "page": 1,
          "perPage": 2,
          "totalPages": 576,
          "results": [
            {
              "_id": "658b694505a6bcd9b9379466",
              "imgUrl": "https://www.nytimes.com/images/2023/04/16/magazine/16mag-LOR/16mag-LOR-blog480.jpg",
              "title": "What I Learned Dogsitting for New York City’s Opulent Elite",
              "text": "In a city of yawning class inequality, some side hustles let you glimpse how the other half lives.",
              "date": "2023-04-11T09:00:18+0000",
              "url": "https://www.nytimes.com/2023/04/11/magazine/dogsitting-rich-new-york.html",
              "id": "nyt://article/8d29f1fc-d146-509d-8ceb-5a5b17d7886b"
            },
            {
              "_id": "658b694505a6bcd9b9379467",
              "imgUrl": "https://www.nytimes.com/images/2023/04/04/multimedia/00VIRTUAL-VETS-01b-fmzk/00VIRTUAL-VETS-01b-fmzk-blog480.jpg",
              "title": "The Virtual Vet Will See You Meow",
              "text": "Veterinary telemedicine could help more pet owners access much-needed care and put anxious animals at ease, but challenges remain.",
              "date": "2023-04-07T09:00:46+0000",
              "url": "https://www.nytimes.com/2023/04/07/health/vet-pet-health-telemedicine.html",
              "id": "nyt://article/992f2f7f-793c-5553-b722-348625f53a4b"
            }
          ]
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
